install automake
install coreutils
install corkscrew
install faad2
install ffmpeg
install fontforge
install git
install gnutls
install imagemagick
install libao
install libgcrypt
install libksba
install libvo-aacenc
install libyaml
install mad
install phantomjs
install python
install python3
install the_silver_searcher
install tmux
install ttfautohint
install zlib
