# Minimal tmux config for server environments - core bindings only.

# Rebinding the pane splitting bindings
bind | split-window -h
bind - split-window -v

# map Vi movement keys as pane movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# and use C-h and C-l to cycle thru panes
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# resize panes using PREFIX H, J, K, L
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Syncronize Panes
bind-key S set-window-option synchronize-pane

set-option -g default-shell $SHELL

# Enable truecolor https://dandavison.github.io/delta/24-bit-color-truecolor.html
set -ga terminal-overrides ",xterm-256color:Tc"

# Reload source file
bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded"
